### ISSUE TITLE
StreamScope: Continuous Reliable Distributed Processing of Big Data Streams

### ISSUE THREAD

**Issue by xldrx** [xldrx/reading_group#29]

**Comment by s-noghabi** [comment]
Building a reliable stream processing by introducing in the DAG of the job:
1) reliable channel, which I feel is exactly the same as Kafka
2) reliable vertices, which the periodically take a snapshot of the vertex state and the messages on-the-fly (currently being processed & being sent out). If failures happen they will go to the latest snapshot, and if they want to replay from some point in the past you can go to  previous snapshot

I do not see any novelty in their work... just reintroducing some basic concepts in stream processing, taken from some system already having them
